addons:
  sonarcloud:
    organization: "sinanegitim-github" # the key of the org you chose at step #3
    token:
      secure: "50ce19a70d75709cfb4e08f3cbebffdd0a961a5b" # encrypted value of your token
jdk:
  - oraclejdk9
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=sinanegitim
